name: "Test and Fuzz AP World"

on:
  - "push"
  - "pull_request"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "ubuntu-latest"
            name: "Linux"
            pyversion: "3.12"
          - os: "macos-latest"
            name: "macOS"
            pyversion: "3.11"
          - os: "windows-latest"
            name: "windows"
            pyversion: "3.12"

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}

    steps:          
      - name: Checkout Archipelago
        uses: actions/checkout@v6
        with:
          repository: ArchipelagoMW/Archipelago
          fetch-depth: 0
          path: .
          
      - name: Checkout AP world
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          path: AP-SamusReturns
          
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.pyversion }}
          cache: pip

      - name: Install AP world
        run: ln -s "$PWD/AP-SamusReturns/src/msr" worlds/msr
        shell: bash

      - name: Install Python Deps
        run: |
          python -m pip install --upgrade pip
          python ModuleUpdate.py --yes --force
          python Launcher.py --update_settings
          python -m pip install pytest
          python -m pip install -r AP-SamusReturns/requirements.txt
        shell: bash

      - name: Run AP tests
        uses: dariocurr/pytest-summary@v2.6
        with:
          extensions: pytest-subtests pytest-xdist
          options: -n auto
          show: "all"

      - name: Fuzz AP World
        uses: pyrox0/apworld-fuzzer-action@v1
        with:
          world: msr
          num_gens: 100
